version: "3"

services: 
        
    socket:
        container_name: socket
        build:
            context: ./src/services/chat
            dockerfile: Dockerfile
        image: api-socket-telegram
        ports:
            - 6000:6000
        links:
            - db
        depends_on: 
            - db
        volumes: 
            - ./src/services/chat:/app/service
        command: /bin/sh /app/service/scripts/execute-socket.sh

    graphql:
        container_name: graphql
        build:
            context: .
            dockerfile: Dockerfile
        image: api-graphql-bebidas
        ports:
            - 4000:4000
        links:
            - db
        depends_on: 
            - db
        volumes: 
            - ./:/app/api
        command: /bin/sh /app/api/scripts/execute-graphql.sh
        
    
    local_tunnel_socket:
        container_name: local_tunel_socket
        build:
            context: ./dockerfiles
            dockerfile: localtunnel.dockerfile
        image: sv-localtunnel
        links:
            - socket
        depends_on: 
            - socket
        command: "lt -p 6000 -l socket -s socket"

    local_tunnel_graphql:
        container_name: local_tunel_graphql
        build:
            context: ./dockerfiles
            dockerfile: localtunnel.dockerfile
        image: sv-localtunnel
        links:
            - graphql
        depends_on: 
            - graphql
        command: "lt -p 4000 -l graphql -s graphql"

    db:
        container_name: database
        image: mongo
        ports: [27017:27017]
        restart: always

    # duckdns:
    #     image: ghcr.io/linuxserver/duckdns
    #     container_name: duckdns
    #     environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=America/Argentina/Buenos_Aires
    #         - SUBDOMAINS=api-nodejs
    #         - TOKEN=da2f6407-850a-4866-9d46-a8533f0ca05c
    #         - LOG_FILE=false
    #     volumes:
    #         - ./src/sv_configs/duckdns/config:/config
    #     restart: unless-stopped
