version: "3"

services: 
    duckdns:
        image: ghcr.io/linuxserver/duckdns
        container_name: duckdns
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Argentina/Buenos_Aires
            - SUBDOMAINS=api-nodejs
            - TOKEN=da2f6407-850a-4866-9d46-a8533f0ca05c
            - LOG_FILE=false
        volumes:
            - ./src/sv_configs/duckdns/config:/config
        restart: unless-stopped
        
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        image: api-graphql
        ports:
            - "3000:3000"
        depends_on: 
            - db
        # volumes:
        #     - "/app/node_modules"
        #     - ./prueba-fronted/:/app

    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src/sv_configs/ssl/certificates:/etc/letsencrypt/live/api-nodejs.duckdns.org
            - ./src/sv_configs/nginx-conf:/etc/nginx/conf.d
            - ./src/sv_configs/ssl/dhparam:/etc/ssl/certs
        depends_on:
            - api
            - duckdns

    db:
        container_name: database
        image: mongo
        ports: [27017:27017]
        restart: always